#pragma once
#define PK_SERIALIZE_HEADER
#include "ISerializer.h"
#include "Common.h"
#include "Serializers/SerializeScalar.h"
#include "Serializers/SerializeEnum.h"
#include "Serializers/SerializeFixedString.h"
#include "Serializers/SerializeArrayList.h"
#include "Serializers/SerializeMathTypes.h"
#include "Serializers/SerializeAsset.h"
#include "Serializers/SerializeCVariablesYaml.h"
#include "Serializers/SerializeInputKeyBindings.h"
#include "Serializers/SerializeMaterialTarget.h"
#undef PK_SERIALIZE_HEADER