#pragma once
#include "vulkan/vulkan.h"

extern PFN_vkSetDebugUtilsObjectNameEXT pk_vkSetDebugUtilsObjectNameEXT;
#define vkSetDebugUtilsObjectNameEXT pk_vkSetDebugUtilsObjectNameEXT

extern PFN_vkSetDebugUtilsObjectTagEXT pk_vkSetDebugUtilsObjectTagEXT;
#define vkSetDebugUtilsObjectTagEXT pk_vkSetDebugUtilsObjectTagEXT

extern PFN_vkQueueBeginDebugUtilsLabelEXT pk_vkQueueBeginDebugUtilsLabelEXT;
#define vkQueueBeginDebugUtilsLabelEXT pk_vkQueueBeginDebugUtilsLabelEXT

extern PFN_vkQueueEndDebugUtilsLabelEXT pk_vkQueueEndDebugUtilsLabelEXT;
#define vkQueueEndDebugUtilsLabelEXT pk_vkQueueEndDebugUtilsLabelEXT

extern PFN_vkQueueInsertDebugUtilsLabelEXT pk_vkQueueInsertDebugUtilsLabelEXT;
#define vkQueueInsertDebugUtilsLabelEXT pk_vkQueueInsertDebugUtilsLabelEXT

extern PFN_vkCmdBeginDebugUtilsLabelEXT pk_vkCmdBeginDebugUtilsLabelEXT;
#define vkCmdBeginDebugUtilsLabelEXT pk_vkCmdBeginDebugUtilsLabelEXT

extern PFN_vkCmdEndDebugUtilsLabelEXT pk_vkCmdEndDebugUtilsLabelEXT;
#define vkCmdEndDebugUtilsLabelEXT pk_vkCmdEndDebugUtilsLabelEXT

extern PFN_vkCmdInsertDebugUtilsLabelEXT pk_vkCmdInsertDebugUtilsLabelEXT;
#define vkCmdInsertDebugUtilsLabelEXT pk_vkCmdInsertDebugUtilsLabelEXT

extern PFN_vkCreateDebugUtilsMessengerEXT pk_vkCreateDebugUtilsMessengerEXT;
#define vkCreateDebugUtilsMessengerEXT pk_vkCreateDebugUtilsMessengerEXT

extern PFN_vkDestroyDebugUtilsMessengerEXT pk_vkDestroyDebugUtilsMessengerEXT;
#define vkDestroyDebugUtilsMessengerEXT pk_vkDestroyDebugUtilsMessengerEXT

extern PFN_vkSubmitDebugUtilsMessageEXT pk_vkSubmitDebugUtilsMessageEXT;
#define vkSubmitDebugUtilsMessageEXT pk_vkSubmitDebugUtilsMessageEXT

extern PFN_vkCreateAccelerationStructureKHR pk_vkCreateAccelerationStructureKHR;
#define vkCreateAccelerationStructureKHR pk_vkCreateAccelerationStructureKHR

extern PFN_vkDestroyAccelerationStructureKHR pk_vkDestroyAccelerationStructureKHR;
#define vkDestroyAccelerationStructureKHR pk_vkDestroyAccelerationStructureKHR

extern PFN_vkCmdSetRayTracingPipelineStackSizeKHR pk_vkCmdSetRayTracingPipelineStackSizeKHR;
#define vkCmdSetRayTracingPipelineStackSizeKHR pk_vkCmdSetRayTracingPipelineStackSizeKHR

extern PFN_vkCmdTraceRaysIndirectKHR pk_vkCmdTraceRaysIndirectKHR;
#define vkCmdTraceRaysIndirectKHR pk_vkCmdTraceRaysIndirectKHR

extern PFN_vkCmdTraceRaysKHR pk_vkCmdTraceRaysKHR;
#define vkCmdTraceRaysKHR pk_vkCmdTraceRaysKHR

extern PFN_vkCreateRayTracingPipelinesKHR pk_vkCreateRayTracingPipelinesKHR;
#define vkCreateRayTracingPipelinesKHR pk_vkCreateRayTracingPipelinesKHR

extern PFN_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR pk_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR;
#define vkGetRayTracingCaptureReplayShaderGroupHandlesKHR pk_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR

extern PFN_vkGetRayTracingShaderGroupHandlesKHR pk_vkGetRayTracingShaderGroupHandlesKHR;
#define vkGetRayTracingShaderGroupHandlesKHR pk_vkGetRayTracingShaderGroupHandlesKHR

extern PFN_vkGetRayTracingShaderGroupStackSizeKHR pk_vkGetRayTracingShaderGroupStackSizeKHR;
#define vkGetRayTracingShaderGroupStackSizeKHR pk_vkGetRayTracingShaderGroupStackSizeKHR

extern PFN_vkGetAccelerationStructureDeviceAddressKHR pk_vkGetAccelerationStructureDeviceAddressKHR;
#define vkGetAccelerationStructureDeviceAddressKHR pk_vkGetAccelerationStructureDeviceAddressKHR

extern PFN_vkGetAccelerationStructureBuildSizesKHR pk_vkGetAccelerationStructureBuildSizesKHR;
#define vkGetAccelerationStructureBuildSizesKHR pk_vkGetAccelerationStructureBuildSizesKHR

extern PFN_vkCmdBuildAccelerationStructuresKHR pk_vkCmdBuildAccelerationStructuresKHR;
#define vkCmdBuildAccelerationStructuresKHR pk_vkCmdBuildAccelerationStructuresKHR

extern PFN_vkCmdCopyAccelerationStructureKHR pk_vkCmdCopyAccelerationStructureKHR;
#define vkCmdCopyAccelerationStructureKHR pk_vkCmdCopyAccelerationStructureKHR

extern PFN_vkCmdPipelineBarrier2KHR pk_vkCmdPipelineBarrier2KHR;
#define vkCmdPipelineBarrier2KHR pk_vkCmdPipelineBarrier2KHR

extern PFN_vkCmdWriteAccelerationStructuresPropertiesKHR pk_vkCmdWriteAccelerationStructuresPropertiesKHR;
#define vkCmdWriteAccelerationStructuresPropertiesKHR pk_vkCmdWriteAccelerationStructuresPropertiesKHR


namespace PK::Rendering::VulkanRHI::Utilities
{
    void VulkanBindExtensionMethods(VkInstance instance);
}